version: '3'

services:
  open-education-db:
    container_name: open-education-db
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    networks:
      - base_network
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  open-education-api:
    container_name: open-education-api
    image: node:lts
    networks:
      - base_network
    ports:
      - 3333:3333
    command: sh -c "npm run start:dev"
    depends_on:
      - open-education-db
    working_dir: /app
    volumes:
      - ./open-education-backend:/app
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@open-education-db:5432/${POSTGRES_DB}

  open-education-web:
    container_name: open-education-web
    image: node:lts
    networks:
      - base_network
    ports:
      - 5173:5173
    command: sh -c "npm install && npm run dev"
    working_dir: /web
    volumes:
      - ./open-education-web:/web
    env_file: .env

networks:
  base_network:


volumes:
  db-data:
